### ISSUE TITLE
I don't even have the words to describe it!

### ISSUE THREAD

**Issue by Jenoclip** [chronicleroflegends/DirectionalSpriteBatchRender#2]
How's that
![image](https://user-images.githubusercontent.com/105174554/234999284-7b7cb483-386b-4a12-b540-e5b8c3e6b2c4.png)
Making sprites like that?
![BPZ0A1](https://user-images.githubusercontent.com/105174554/234999335-fb9c29c1-66bc-42b8-a7aa-c436454226c5.png)
![BPZ0A2](https://user-images.githubusercontent.com/105174554/234999338-dff0eaa8-ace4-4061-8503-3f5eb1f2561d.png)
![BPZ0A3](https://user-images.githubusercontent.com/105174554/234999342-ece05b59-d889-417c-99a8-91fc2125738d.png)
![BPZ0A4](https://user-images.githubusercontent.com/105174554/234999344-2d1e5ae4-f8c1-42a2-bc40-0e5d6625e4c7.png)
![BPZ0A5](https://user-images.githubusercontent.com/105174554/234999346-45789c32-924c-4e6a-9aaf-80e6e955b337.png)
![BPZ0A6](https://user-images.githubusercontent.com/105174554/234999348-8d6e5033-c93d-4f6b-9ed7-a3e0c7b1d39f.png)
![BPZ0A7](https://user-images.githubusercontent.com/105174554/234999349-e271d837-36b3-45c8-b8e6-632355a98dc5.png)
![BPZ0A8](https://user-images.githubusercontent.com/105174554/234999352-eecea28f-36aa-4b92-a3d9-3f7a4ff4db4a.png)
I spent HUGE amounts of time on different positioning and configurations, each time I got more and more cursed sprites.
HL 2's poison zombie, animation walk time code 24, it was fine without animation

**Comment by IlyStra** [comment]
HL 2's poison zombie, animation walk time code 24, it was fine without animations.

**Comment by Jenoclip** [comment]
I see what the problem is. Animation bones are not attached to the Rotation Origin, as a result, polygons broke when rotating a poisonous zombie.
